### ISSUE TITLE
Cannot find name 'BluetoothLEScanFilter'

### ISSUE THREAD

**Issue by christianlmc** [vueuse/vueuse#1709]
### Describe the bug

Describe the bug
When running `tsc --noEmit` I get the following error:

```
node_modules/@vueuse/core/index.d.ts(340,15): error TS2304: Cannot find name 'BluetoothLEScanFilter'.
node_modules/@vueuse/core/index.d.ts(348,24): error TS2304: Cannot find name 'BluetoothServiceUUID'.
node_modules/@vueuse/core/index.d.ts(376,36): error TS2304: Cannot find name 'BluetoothRemoteGATTServer'.
node_modules/@vueuse/core/index.d.ts(378,42): error TS2304: Cannot find name 'BluetoothServiceUUID'.
node_modules/@vueuse/core/index.d.ts(378,75): error TS2304: Cannot find name 'BluetoothRemoteGATTService'.
node_modules/@vueuse/core/index.d.ts(379,44): error TS2304: Cannot find name 'BluetoothServiceUUID'.
node_modules/@vueuse/core/index.d.ts(379,89): error TS2304: Cannot find name 'BluetoothRemoteGATTService'.
node_modules/@vueuse/core/index.d.ts(383,41): error TS2304: Cannot find name 'WatchAdvertisementsOptions'.
node_modules/@vueuse/core/index.d.ts(387,63): error TS2304: Cannot find name 'BluetoothDevice'.
node_modules/@vueuse/core/index.d.ts(388,62): error TS2304: Cannot find name 'BluetoothDevice'.
node_modules/@vueuse/core/index.d.ts(388,83): error TS2304: Cannot find name 'BluetoothAdvertisingEvent'.
node_modules/@vueuse/core/index.d.ts(393,41): error TS2304: Cannot find name 'BluetoothDevice'.
node_modules/@vueuse/core/index.d.ts(393,62): error TS2304: Cannot find name 'BluetoothAdvertisingEvent'.
node_modules/@vueuse/core/index.d.ts(394,42): error TS2304: Cannot find name 'BluetoothDevice'.
node_modules/@vueuse/core/index.d.ts(395,46): error TS2304: Cannot find name 'BluetoothDevice'.
node_modules/@vueuse/core/index.d.ts(396,32): error TS2304: Cannot find name 'BluetoothDevice'.
node_modules/@vueuse/core/index.d.ts(397,34): error TS2304: Cannot find name 'BluetoothDevice'.
node_modules/@vueuse/core/index.d.ts(398,34): error TS2304: Cannot find name 'BluetoothDevice'.
node_modules/@vueuse/core/index.d.ts(401,26): error TS2304: Cannot find name 'BluetoothRemoteGATTServer'.
```

### Relevant packages and their respective version:
```
"typescript": "^4.7.4",
"@vueuse/core": "^8.7.4",
```

### Reproduction

On a fresh install, just navigate to node_modules/@vueuse/core/index.d.ts and search for bluetooth stuff

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 4.77 GB / 15.50 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 101.0.1
  npmPackages:
    @vueuse/core: ^8.7.4 => 8.7.4 
    vue: ^2.6.12 => 2.6.14
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by webfansplz** [comment]
Fixed in [9f5b9ef](https://github.com/vueuse/vueuse/commit/9f5b9efaf08b7bbe29f0dcf081c8464e50abe7c0),But we may need to update the package version. cc @antfu

**Comment by antfu** [comment]
`v8.7.5` released

**Comment by joneath** [comment]
We had the same issue as @moneybagscleary on both the app and storybook build but by just adding `web-bluetooth` to our `tsconfig.json`'s types array fixed it and no dependency install needed.

**Comment by arthurfiorette** [comment]
Hey @antfu, I'm still getting this error. For now, adding `@types/web-bluetooth` to the dev dependencies work, but it shouldn't be the final solution for this problem.

This error is being raised because no references to `@types/web-bluetooth` is being made in the source code and it's being expected that this dependency gets loaded at runtime to make all Bluetooth... types available.

Probably this could be fixed by adding a `///<reference types="@types/web-bluetooth" />` [reference](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) into the definitions file. I tried creating a PR for it, but the build/bundle step removed it anyways... Could you add it manually?

**Comment by zymotik** [comment]
To fix, I used @stephanemagnenat's code in my project:

`./src/vite-env.d.ts`
```ts
/// <reference types="@types/web-bluetooth" />
```

**Comment by Anoesj** [comment]
This is not fixed at all. "Solutions" are not acceptable for normal users. Can someone reopen this?

**Comment by OrbisK** [comment]
> This is not fixed at all. "Solutions" are not acceptable for normal users. Can someone reopen this?

please open an new issue. try to link a good reproduction please

**Comment by Anoesj** [comment]
I'm sorry, but why a new issue? This is the exact issue me and others keep running into. In any project using VueUse with TypeScript and vue-tsc, I run into these specific errors. Haven’t you run into them in yours?

Edit: with `skipLibCheck: false` only of course.

**Comment by OrbisK** [comment]
Here are some workarounds/mentioned fixes that have worked for other people + everyone will be notified when we discuss your reproduction here.
